# Generated by Django 4.1 on 2024-09-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usernotification_eventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Started'), ('FAILURE', 'Failure'), ('SUCCESS', 'Completed'), ('RETRY', 'Retrying')], default='STARTED', max_length=10),
        ),
    ]
