# Generated by Django 4.1 on 2024-09-12 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_eventlog_message_alter_eventlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
